# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:
- task: AzureFileCopy@3
  inputs:
    SourcePath: ExampleAppDeploy
    azureSubscription: 'Azure로운 생활(a791ad38-5fa2-447d-8833-460ee318d917)'
    Destination: AzureBlob
    storage: newsatest
    ContainerName: newdemocontainer

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure로운 생활(a791ad38-5fa2-447d-8833-460ee318d917)'
    subscriptionId: 'a791ad38-5fa2-447d-8833-460ee318d917'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'arm_cicd_demo'
    location: 'Korea Central'
    templateLocation: 'Linked artifact'
    csmFile: 'ExampleAppDeploy/WebSite.json'
    csmParametersFile: 'ExampleAppDeploy/WebSite.parameters.json'
    deploymentMode: 'Incremental'